### ISSUE TITLE
clicking execute should take me to the execution table

### ISSUE THREAD

**Issue by juancarlosfarah** [graasp/graasp-insights#86]
Upon completion of execution, I would expect the user to be sent to the results screen.

**Comment by juancarlosfarah** [comment]
Actually, I would have it redirect to the executions table suggested in #87 .

**Comment by pyphilia** [comment]
This issue might be closed with #44

**Comment by hagoptaminian** [comment]
This is now outdated. In the executions tab, there is now an executions table through which one can click through to the result (when the execution is completed).
